import { AchievementCardData } from "./types";

export const mockAchievementCards: AchievementCardData[] = [
  {
    id: "kinmen-dissertation",
    title: "Threat Perception and Ontological Security in Kinmen",
    subtitle: "LSE MSc IR Dissertation Project",
    category: "Research",
    tags: [
      "International Relations",
      "Taiwan Strait",
      "Borderland Security",
      "Ontological Security",
      "Qualitative Research",
    ],
    status: "Developing",
    progress: 58,
    currentValue:
      "Analyses Taiwan Strait security through borderland identity and ontological security, showing how proximity to threat can produce de-escalatory rather than hostile security reasoning.",
    skills: [
      "IR Theory",
      "Taiwan Strait Security",
      "Discourse Analysis",
      "Qualitative Research",
      "Borderland Security",
    ],
    nextFillAction:
      "Write the methodology section: case selection, data, methods, justification.",
    resumeBullet:
      "Conducted MSc dissertation research on threat perception and ontological security in Kinmen, analysing how borderland identity, historical vulnerability, and cross-Strait livelihood ties shape local security reasoning.",
    linkedinVersion: "",
    interviewStory: "",
    portfolioDescription: "",
    targetCareerPaths: ["international relations / policy", "geopolitical risk analytics"],
    createdAt: "2026-07-07T17:42:00+08:00",
    updatedAt: "2026-07-07T17:42:00+08:00",
    timeline: [
      {
        id: "event-kinmen-1",
        type: "card_created",
        label: "Card created",
        description: "Created dissertation achievement card from LSE dissertation progress.",
        actor: "system",
        createdAt: "2026-07-07T17:42:00+08:00",
        newProgress: 58,
      },
    ],
    evidence: [
      {
        id: "evidence-kinmen-1",
        title: "Discourse analysis pilot",
        description:
          "Pilot analysis of 38 Kinmen Daily editorials identifying five organising themes.",
        type: "note",
        source: "",
        createdAt: "2026-06-20T12:00:00+08:00",
        updatedAt: "2026-06-20T12:00:00+08:00",
      },
    ],
    missingEvidence: [
      {
        id: "missing-kinmen-1",
        title: "Methodology proof",
        description: "Add methodology notes or supervisor feedback to support research rigor.",
        status: "missing",
        createdAt: "2026-07-07T17:42:00+08:00",
        updatedAt: "2026-07-07T17:42:00+08:00",
      },
    ],
  },
  {
    id: "yardenportal-prototype",
    title: "YardenPORTAL Intelligence Desk Prototype",
    subtitle: "International News Tracking & Draft Generation Platform",
    category: "Product",
    tags: [
      "International Relations",
      "News Intelligence",
      "Automation",
      "AI Workflow",
      "Geopolitics",
      "Product",
    ],
    status: "Validated",
    progress: 75,
    currentValue:
      "Built a working prototype that turns international news monitoring, topic scoring, and AI-assisted draft generation into a structured Traditional Chinese briefing workflow.",
    skills: [
      "Product Thinking",
      "News Intelligence",
      "AI Workflow",
      "Geopolitical Analysis",
      "Content Strategy",
    ],
    nextFillAction:
      "整理一頁 prototype case study：problem, solution, workflow, features, and roadmap.",
    resumeBullet:
      "Built a working prototype of YardenPORTAL Intelligence Desk, an AI-assisted international news tracking and draft generation platform using topic scoring, RSS ingestion, and structured Traditional Chinese briefing workflows.",
    linkedinVersion: "",
    interviewStory: "",
    portfolioDescription: "",
    targetCareerPaths: ["product / automation workflow", "geopolitical risk analytics"],
    createdAt: "2026-07-07T17:45:00+08:00",
    updatedAt: "2026-07-07T17:45:00+08:00",
    timeline: [
      {
        id: "event-yarden-1",
        type: "card_created",
        label: "Card created",
        description: "Created product achievement card from YardenPORTAL prototype progress.",
        actor: "system",
        createdAt: "2026-07-07T17:45:00+08:00",
        newProgress: 75,
      },
    ],
    evidence: [
      {
        id: "evidence-yarden-1",
        title: "Prototype stack",
        description:
          "Next.js, Tailwind CSS, Supabase, RSS ingest, topic scoring rules, and AI draft generation workflow.",
        type: "note",
        source: "",
        createdAt: "2026-06-25T12:00:00+08:00",
        updatedAt: "2026-06-25T12:00:00+08:00",
      },
    ],
    missingEvidence: [
      {
        id: "missing-yarden-1",
        title: "User proof",
        description: "Add one screenshot or walkthrough of the actual prototype flow.",
        status: "missing",
        createdAt: "2026-07-07T17:45:00+08:00",
        updatedAt: "2026-07-07T17:45:00+08:00",
      },
    ],
  },
  {
    id: "soft-furnishing-side-business",
    title: "軟裝設計副業養成",
    subtitle: "從 0 建立空間美學、SketchUp、AI 視覺提案與租屋小宅改裝接案能力",
    category: "Side Business Asset / Productized Service",
    tags: [
      "SoftFurnishing",
      "InteriorStyling",
      "SketchUp",
      "AIVisualisation",
      "SideBusiness",
      "AestheticCapital",
      "RentalMakeover",
      "SmallApartmentDesign",
      "MarketDrivenTraining",
    ],
    status: "In Progress",
    progress: 8,
    currentValue:
      "目前已完成軟裝設計作為副業的可行性分析，初步確認「軟裝設計」比「完整室內設計」更適合作為副業起點；已建立 SketchUp + AI 的學習方向，並將初期訓練方向調整為更貼近市場需求的「租屋小宅改裝」，面向租屋族、小坪數住戶、年輕上班族、研究生與知識工作者。",
    skills: [
      "空間美學判斷",
      "生活方式分析",
      "產品化服務思維",
      "AI 視覺提案",
      "SketchUp 基礎規劃",
      "租屋改造策略",
      "小坪數空間配置",
      "採購清單規劃",
      "預算分級",
      "個人品牌定位",
    ],
    nextFillAction:
      "在 30 天內完成第一個 SketchUp 小宅模型，主題為「租屋小宅改裝：低預算、高質感、可執行的空間升級方案」。",
    resumeBullet:
      "Developed a market-oriented side-project roadmap for a soft furnishing and rental small-apartment makeover service, integrating SketchUp modelling, AI visualisation, moodboard creation, productised consulting packages, budget planning, and procurement recommendations for renters, small-space residents, and young professionals.",
    linkedinVersion: "",
    interviewStory: "",
    portfolioDescription:
      "正在養成中的市場導向副業能力卡：以租屋小宅軟裝為切入點，訓練 SketchUp、AI 視覺提案、採購顧問、預算分級與產品化服務能力。",
    targetCareerPaths: ["product / automation workflow", "data analytics"],
    createdAt: "2026-07-01T09:00:00+08:00",
    updatedAt: "2026-07-08T00:55:00+08:00",
    timeline: [
      {
        id: "event-soft-furnishing-1",
        type: "card_created",
        label: "Timeline start",
        description: "Started soft furnishing side-business capability development track.",
        actor: "system",
        createdAt: "2026-07-01T09:00:00+08:00",
        newProgress: 8,
      },
    ],
    evidence: [
      {
        id: "evidence-soft-furnishing-1",
        title: "軟裝設計副業可行性分析",
        description:
          "已完成軟裝設計副業可行性分析；已釐清 SketchUp 與 AI 的差異；已確認初期路線為「軟裝、租屋小宅改裝、小坪數配置、AI 視覺提案、採購顧問」，而非完整室內裝修或施工監工。",
        type: "note",
        source: "",
        createdAt: "2026-07-08T00:55:00+08:00",
        updatedAt: "2026-07-08T00:55:00+08:00",
      },
    ],
    missingEvidence: [
      {
        id: "missing-soft-furnishing-1",
        title: "第一個 SketchUp 租屋小宅模型",
        description: "尚未完成第一個 SketchUp 租屋小宅模型。",
        status: "missing",
        createdAt: "2026-07-08T00:55:00+08:00",
        updatedAt: "2026-07-08T00:55:00+08:00",
      },
      {
        id: "missing-soft-furnishing-2",
        title: "作品集與真實案例",
        description: "尚未產出正式作品集，尚未完成真實改造案例。",
        status: "missing",
        createdAt: "2026-07-08T00:55:00+08:00",
        updatedAt: "2026-07-08T00:55:00+08:00",
      },
      {
        id: "missing-soft-furnishing-3",
        title: "服務頁與市場驗證",
        description: "尚未建立服務頁、定價與接案流程；尚未驗證市場需求與付費意願。",
        status: "missing",
        createdAt: "2026-07-08T00:55:00+08:00",
        updatedAt: "2026-07-08T00:55:00+08:00",
      },
    ],
    goal: {
      id: "goal-soft-furnishing-mvp",
      title: "建立租屋小宅軟裝副業 MVP",
      type: "Side Business / Creative Capital / Market-Oriented Training",
      whyItMatters:
        "這個目標可以把 Alex 的美學偏好、AI 工具能力、空間秩序感與產品化服務思維，轉化成可展示、可接案、可長期累積的副業資產。訓練方向不應只服務個人審美，而要面向真實市場需求，尤其是租屋族、小坪數住戶、年輕上班族、研究生與知識工作者對「低預算、可執行、可搬遷、不破壞原屋況」的空間升級需求。",
      successMetric:
        "12 個月內完成 3 個市場導向作品集案例、1 個真實租屋或小宅改造案例、1 個可販售服務頁，並完成至少 1 筆付費案或 3 筆低價測試案。",
      firstMilestone: "完成第一個 SketchUp 租屋小宅模型。",
      currentBlocker:
        "目前尚未開始實作，容易停留在概念分析與個人風格想像階段；需要把審美與工具學習轉化成市場可理解、客戶願意付費的具體服務。",
      nextAction:
        "本週開啟 SketchUp，建立一個 3m × 4m × 2.8m 的租屋小宅房間盒子，並放入基本家具配置，重點是床、書桌、收納、燈光與活動式軟裝。",
      energyLevelRequired: "Medium",
      strategicValue: "Medium-High",
      incomePotential: "初期 NT$3,000-10,000 / 案；成熟後 NT$20,000-50,000+ / 案。",
      identitySignal:
        "從純粹知識工作者，擴展成能把美學、生活系統、市場需求與商業服務結合的人。",
      timelineStart: "2026-07",
      targetReviewDate: "2026-08-08",
      longTermTargetDate: "2027-07-08",
      createdAt: "2026-07-08T00:55:00+08:00",
      updatedAt: "2026-07-08T00:55:00+08:00",
      milestones: [
        {
          id: "goal-soft-furnishing-30d",
          title: "30 天目標：完成第一個租屋小宅改裝軟裝提案",
          deadline: "2026-08-08",
          progressContribution: 20,
          completionCriteria: [
            "完成一個 3m × 4m × 2.8m 的 SketchUp 租屋小宅房間模型",
            "放入床、書桌、椅子、衣架或衣櫃、層架、燈、地毯、窗簾、活動式收納",
            "輸出 3 個視角截圖",
            "製作 1 張 moodboard",
            "做出 NT$10,000 / NT$30,000 / NT$60,000 三版採購清單",
            "標註租屋友善原則：不鑽牆、不破壞、不固定施工、可搬走、可復原",
            "整理成一份簡單 PDF 或 Alex OS Portfolio Card",
          ],
          createdAt: "2026-07-08T00:55:00+08:00",
          updatedAt: "2026-07-08T00:55:00+08:00",
        },
        {
          id: "goal-soft-furnishing-90d",
          title: "90 天目標：完成 3 個市場導向虛擬空間案例",
          deadline: "2026-10-08",
          progressContribution: 35,
          completionCriteria: [
            "完成台北 5 坪租屋改造",
            "完成研究生／年輕上班族小房間升級",
            "完成小宅客廳＋工作區複合空間配置",
            "每個案例包含目標客群、空間問題、預算限制、租屋限制與風格定位",
            "每個案例包含 SketchUp 配置、AI 氛圍圖、採購清單與預算表",
            "每個案例包含 Before / After 邏輯說明與可搬遷／可復原設計原則",
          ],
          createdAt: "2026-07-08T00:55:00+08:00",
          updatedAt: "2026-07-08T00:55:00+08:00",
        },
        {
          id: "goal-soft-furnishing-6m",
          title: "6 個月目標：完成 1-2 個真實租屋或小宅軟裝改造案例",
          deadline: "2027-01-08",
          progressContribution: 25,
          completionCriteria: [
            "找朋友、家人、同學、同事或自己的租屋空間作為案例",
            "完成現場丈量",
            "記錄使用者需求與預算",
            "做出軟裝提案",
            "協助採購或配置",
            "拍攝前後對比",
            "寫成一篇案例文章",
            "收集使用者回饋，確認服務是否真的解決市場需求",
          ],
          createdAt: "2026-07-08T00:55:00+08:00",
          updatedAt: "2026-07-08T00:55:00+08:00",
        },
        {
          id: "goal-soft-furnishing-12m",
          title: "12 個月目標：上架第一個產品化服務",
          deadline: "2027-07-08",
          progressContribution: 20,
          completionCriteria: [
            "推出至少一個可販售服務：NT$3,000 租屋軟裝診斷、NT$6,800 租屋小房間升級方案、NT$9,800 小宅軟裝完整提案、NT$12,000+ AI 視覺化＋SketchUp 配置＋採購清單、或 NT$20,000+ 租屋小宅全案軟裝陪跑",
            "完成至少 1 筆付費案或 3 筆低價測試案",
          ],
          createdAt: "2026-07-08T00:55:00+08:00",
          updatedAt: "2026-07-08T00:55:00+08:00",
        },
      ],
    },
  },
  {
    id: "future-sustainability-consulting",
    title: "Future Sustainability Consulting Project",
    subtitle: "ESG / Climate Consulting Work Simulation",
    category: "Sustainability Consulting",
    tags: ["Sustainability", "ESG", "Climate Consulting", "Stakeholder Research", "Decarbonization"],
    status: "Idea",
    progress: 36,
    currentValue:
      "模擬未來永續顧問工作情境：把企業減碳需求、利害關係人訪談、政策壓力與初步資料盤點整理成可交付的 ESG advisory case。",
    skills: [
      "Sustainability Strategy",
      "ESG Research",
      "Stakeholder Mapping",
      "Climate Risk Framing",
      "Consulting Communication",
    ],
    nextFillAction:
      "補上一個 mock client brief：產業、痛點、目前排放資料、想達成的永續目標。",
    resumeBullet:
      "Developed a sustainability consulting case simulation translating climate risk, stakeholder needs, and decarbonization goals into an ESG advisory workflow.",
    linkedinVersion: "",
    interviewStory: "",
    portfolioDescription: "",
    targetCareerPaths: ["ESG / climate consulting", "finance / sustainable finance", "data analytics"],
    createdAt: "2026-07-08T00:45:00+08:00",
    updatedAt: "2026-07-08T00:45:00+08:00",
    timeline: [
      {
        id: "event-future-sustainability-1",
        type: "card_created",
        label: "Card created",
        description: "Created a mock future sustainability consulting achievement card.",
        actor: "system",
        createdAt: "2026-07-08T00:45:00+08:00",
        newProgress: 36,
      },
    ],
    evidence: [
      {
        id: "evidence-future-sustainability-1",
        title: "Mock consulting scenario",
        description:
          "A future-facing ESG consulting scenario for practicing advisory framing, client diagnosis, and evidence gathering.",
        type: "note",
        source: "",
        createdAt: "2026-07-08T00:45:00+08:00",
        updatedAt: "2026-07-08T00:45:00+08:00",
      },
    ],
    missingEvidence: [
      {
        id: "missing-future-sustainability-1",
        title: "Client brief",
        description: "Add a one-page mock client brief with industry, pain point, and target sustainability outcome.",
        status: "missing",
        createdAt: "2026-07-08T00:45:00+08:00",
        updatedAt: "2026-07-08T00:45:00+08:00",
      },
      {
        id: "missing-future-sustainability-2",
        title: "Evidence of analysis",
        description: "Add one table, screenshot, or structured note showing how the ESG recommendation was formed.",
        status: "missing",
        createdAt: "2026-07-08T00:45:00+08:00",
        updatedAt: "2026-07-08T00:45:00+08:00",
      },
    ],
  },
  {
    id: "cbam-investment-report",
    title: "CBAM 對台灣鋼鐵業投資研究報告",
    subtitle: "CBAM Investment Research",
    category: "ESG × Finance",
    tags: ["ESG", "Finance", "EU Policy", "CBAM", "Steel Industry"],
    status: "Developing",
    progress: 28,
    currentValue:
      "將 EU CBAM 政策轉換成台灣鋼鐵產業的投資風險分析，展現 ESG regulation、sector research 與 financial reasoning 能力。",
    skills: [
      "ESG Regulation",
      "Sector Research",
      "Financial Analysis",
      "Policy Analysis",
      "Data Interpretation",
    ],
    nextFillAction: "新增中鋼、台泥、亞泥近三年的營收與毛利率資料。",
    resumeBullet:
      "Developed an ESG investment research project analysing CBAM-related transition risks for Taiwan’s high-carbon industries.",
    linkedinVersion: "",
    interviewStory: "",
    portfolioDescription: "",
    targetCareerPaths: ["ESG / climate consulting", "finance / sustainable finance"],
    createdAt: "2026-07-07T17:50:00+08:00",
    updatedAt: "2026-07-07T17:50:00+08:00",
    timeline: [
      {
        id: "event-cbam-1",
        type: "card_created",
        label: "Card created",
        description: "Created CBAM investment research card from project idea.",
        actor: "system",
        createdAt: "2026-07-07T17:50:00+08:00",
        newProgress: 28,
      },
    ],
    evidence: [],
    missingEvidence: [
      {
        id: "missing-cbam-1",
        title: "Company financials",
        description: "Add three years of revenue and gross margin data for target firms.",
        status: "missing",
        createdAt: "2026-07-07T17:50:00+08:00",
        updatedAt: "2026-07-07T17:50:00+08:00",
      },
      {
        id: "missing-cbam-2",
        title: "Policy-to-investment link",
        description: "Show how CBAM translates into a concrete investment thesis or risk framing.",
        status: "missing",
        createdAt: "2026-07-07T17:50:00+08:00",
        updatedAt: "2026-07-07T17:50:00+08:00",
      },
    ],
  },
];
